In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
df = pd.read_csv("Cross_sport_selection_data.csv")
X = df[['vo2_max']]
y = df['skiing_potential']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Linear Regression")
print("Coefficient:", model.coef_[0])
print("Intercept:", model.intercept_)
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))

Linear Regression
Coefficient: -0.031390840596741756
Intercept: 81.76478693972632
R2 Score: 0.0014581578251456895
Mean Squared Error: 135.4811219414545


PICKLE PACKAGE

In [ ]:
import pickle

In [ ]:
with open('model_pickle','wb') as file:
    pickle.dump(model,file)

In [ ]:
with open('model_pickle','rb') as file:
    mp = pickle.load(file)

In [ ]:
mp.coef_

array([-0.03139084])

In [ ]:
mp.intercept_

np.float64(81.76478693972632)

In [ ]:
mp.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-75.18941604])

JOBLIB PACKAGE

In [ ]:
import joblib

In [ ]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [ ]:
mj = joblib.load('model_joblib')

In [ ]:
mj.coef_

array([-0.03139084])

In [ ]:
mj.intercept_

np.float64(81.76478693972632)

In [ ]:
mj.predict([[5000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([-75.18941604])

ONE HOT ENCODING

In [ ]:
import pandas as pd
df = pd.read_csv("Cross_sport_selection_data.csv")
print("Original Dataset:")
print(df.head())
encoded_df = pd.get_dummies(
    df,
    columns=['sport', 'gender'],
    drop_first=False
)
print("\nEncoded Dataset:")
print(encoded_df.head())
encoded_df.to_csv("encoded_cross_sport_data.csv", index=False)

Original Dataset:
  athlete_id    sport  age gender  training_years  vo2_max   hrv  \
0      A0001  running   24      M               6     56.9  86.6   
1      A0002  cycling   22      F              14     73.3  84.7   
2      A0003  running   25      M               1     59.1  85.0   
3      A0004  running   31      F               9     71.4  71.9   
4      A0005  cycling   30      F               3     56.7  76.6   

   lactate_threshold  stride_length  cadence  force_application  \
0               78.2           1.26      178              243.5   
1               74.7           1.36      165              345.2   
2               86.7           1.10      195              216.2   
3               82.4           1.19      189              290.2   
4               70.7           1.44      157              335.2   

   performance_score  adaptability_score  skiing_potential  
0               9.12                7.96              77.9  
1               8.56                7.36        

TRAIN TEST SPLIT

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv("Cross_sport_selection_data.csv")
print(df.head())
X = df.drop("skiing_potential", axis=1)
y = df["skiing_potential"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

  athlete_id    sport  age gender  training_years  vo2_max   hrv  \
0      A0001  running   24      M               6     56.9  86.6   
1      A0002  cycling   22      F              14     73.3  84.7   
2      A0003  running   25      M               1     59.1  85.0   
3      A0004  running   31      F               9     71.4  71.9   
4      A0005  cycling   30      F               3     56.7  76.6   

   lactate_threshold  stride_length  cadence  force_application  \
0               78.2           1.26      178              243.5   
1               74.7           1.36      165              345.2   
2               86.7           1.10      195              216.2   
3               82.4           1.19      189              290.2   
4               70.7           1.44      157              335.2   

   performance_score  adaptability_score  skiing_potential  
0               9.12                7.96              77.9  
1               8.56                7.36              85.5  
2    